### ISSUE TITLE
Internal links (and possibly arbitrary components) in rendered HTML

### ISSUE THREAD

**Issue by lolmaus** [johnotander/ember-remarkable#19]
Hi.

My markdown content has cross-references. I want them to behave like internal links between routes.

I think ember-remarkable could optionally run rendered HTML through Ember template compiler to leverage `{{link-to}}`s and other components.

Or maybe there's a better path?

**Comment by johnotander** [comment]
I definitely think there should be a way in which we can support this. Not sure how this would work, but optionally running through the template compiler could work well (I'd have to do a bit of digging to see how feasible this is).

The `{{link-to}}` parser in place of the default `linkify` option could potentially work as a custom plugin [#7], which can be pulled in.

**Comment by lolmaus** [comment]
Ember template compiler transforms a string to a function, there's no way you can use it as a Remarkable plugin.

**Comment by johnotander** [comment]
I mean as a plugin to transform markdown output like

```html
<a href="/some-link">Some Link</a>
```

To

```html
{{#link-to 'some-link}}Some Link{//link-to}}
```

But, after rereading your issue I think I may have misunderstood you. From what I gather now you're referring to `{{link-to}}` helpers that actually exist in your markdown, correct?

**Comment by lolmaus** [comment]
@johnotander My links appear as `{{#crossLink "myClass:method"}}{{/crossLink}}` where `myClass` is an URL segment and `method` is a child route name.

I can regex them into `<a>`s or `{{link-to}}`s, whatever.

What I meant is that the result should be internal links handled by Ember (behave like `{{link-to}}`s). Not just `<a>`s with relative URLs.
